### ISSUE TITLE
How to export the serving input function as a protobuf(pb) file?

### ISSUE THREAD

**Issue by Madhivarman** [vincentteyssier/tf.estimator_tutorial#1]
Thanks for this awesome tutorial. I have doubt, How do we serve the input function for this model and export the (.pb) file. So we can upload the (.pb) file to the Google cloud and get predictions from the cloud components. To serve the input function, I  wrote this code

```
def serving_input_fn():
    feature_placeholders = {
      'var1' : tf.placeholder(tf.float32, [None]),
      'var2' : tf.placeholder(tf.float32, [None]),
      ...
    }
    features = {
        key: tf.expand_dims(tensor, -1)
        for key, tensor in feature_placeholders.items()
    }
    return tf.estimator.export.ServingInputReceiver(features, 
                                                    feature_placeholders)
```

How do I export this serving input function and save as protobuf file? To export the file, I used

```
export_dir = '<folder_path>'
classifier.export_savedmodel(export_dir, serving_input_fn)
```
But it throughs following error

> ValueError: export_outputs must be a dict and not<class 'NoneType'>

**Comment by vincentteyssier** [comment]
Thanks but this is not an issue and serving is not in the scope of this tutorial.
A simple google search would have given you your answer though:
[https://stackoverflow.com/questions/48681600/how-to-store-model-in-pb-file-with-estimator-in-tensorflow](https://stackoverflow.com/questions/48681600/how-to-store-model-in-pb-file-with-estimator-in-tensorflow)

**Comment by Madhivarman** [comment]
@vincentteyssier  Thanks!
